### ISSUE TITLE
change Rally to CA Agile Central

### ISSUE THREAD

**Issue by marydavis** [waffleio/waffle.io-takeout#114]
**Acceptance Criteria**
- [ ] change copy in replicated settings
- [ ] change image name to be waffle.io-caac-integration, so the metrics don't say the name of the rally container
  - [ ] may require renaming the repo, which will require reconfiguring waffle, codeship, and quay
  - [ ] may require changing nginx to not use `/integrations/rally` and instead use `/integrations/caac'
  - [ ] change rally integration base url, make sure upgrading from a previous install correctly changes it

**Comment by homeyer** [comment]
blocked until we know the future around Waffle + CAAC, if we go separate directions we'll just rip this out entirely.

**Comment by homeyer** [comment]
removing the rally integration, since we don't have the support of the Agile Management BU right now.
