### ISSUE TITLE
Ability to allow anonymous users to view public boards on private GHE installations

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io-takeout#115]
[Requested here](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/unassigned/conversations/1900409539)

Details:
GH:E installations can be configured to be public or private. Public instances mean that public repos are visible without logging in (anonymous access), like GitHub.com. Private means you must login before seeing any repos, public or private. According to the GHE ToS, you are not permitted to have a public installation that's open to the internet.

For GH:E customers with private installations, it's desired to allow users to see public boards without having to login. 

We can do this, but would require the following work:
- [ ] use the `APPLICATION_ACCESS_TOKEN` in Takeout to access public boards, this is slightly different than how SaaS uses the token for anonymous access.
- [ ] the token needs to be configured somewhere, we may be able to do this programatically, but would need that in an admin interface that we don't have yet.
- [ ] a setting in the admin settings (replicated) that a user can enable/disable this. Default is disabled.

**Comment by rg-net** [comment]
This may loose the ability to track origin of issues. Some may want anonymous requests while others are looking for a simple way to avoid user management. You probably want to find more of the motivation behind this for specific use cases before you start development.

**Comment by lo1tuma** [comment]
@rg-net This issue is only about read-only access for anonymous users. Also this feature is already available when using public github.com repositories on waffle.io but it doesn’t work for public repositories on a github enterprise instance in combination with waffle takeout.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
