### ISSUE TITLE
admin for takeout

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#116]
**Acceptance Criteria**
- [x] our admin app, with a docker file
- [ ] ~~write tests!~~
- [x] authenticated with replicated console auth, figure out how we can do that. Talk to the replicated API to get the username/password?
- [ ] ability to browse projects, not just search
- [ ] ~~🔑see number of seats used~~
- [ ] ~~in the future manage users, be able to see active/inactive, kick users, etc.~~
- [ ] ~~see license info~~
- [ ] ~~allow admins to whitelist logins: this is for teams that don't want anyone to sign up, if they're only paying for their team and want to manage users explicitly.~~

MVP (Ashley's notes)
- [ ] See user names for everyone using Takeout 
- [ ] Have the list of all projects and users 
- [ ] ~~Don't allow for kicking users yet - we can manually expand their license as needed**~~
  - [ ] allow admins to delete accounts
- [ ] ~~Make sure it's easy for _an admin_ to clear users out of their Takeout installation with a query so they can start their license 'fresh'~~
- [ ] **ideally allow an admin to remove users who no longer need access to Takeout or have accessed Takeout from another part of the org or another team and should no longer have access (unless they want to pay for that user.)

**Comment by marydavis** [comment]
should this be marked 'duplicate'?

**Comment by homeyer** [comment]
nope :)
