### ISSUE TITLE
read only users can't see secondary sources

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#118]
To reproduce:
- [x] in an organization, have 2 private repos
- [x]  create a team, where a user only has read access to both repos
- [x] as an admin, create the project with one of the private repos, and add the second to the board as well
- [x] login (incognito, if logged in as an admin elsewhere) as the read only user, and your board will only show the primary repo, not the secondary.

**Comment by homeyer** [comment]
thought: always ask GitHub to know whether a user has permission to a source or not. Right now we only look at the primary repo, and then whether they have public/private permissions.

**Comment by nparsons08** [comment]
Blocked until Andrew fixes repro steps
