### ISSUE TITLE
verify we can connect to replicated integration api

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#123]
The `$REPLICATED_INTEGRATIONAPI` env var tells us where the api is running, but we're not guaranteed to be able to reach it.

If we can't reach it, the takeout-startup process blows up with `Takeout startup failed: Error: connect EHOSTUNREACH 138.42.125.112:9880`, where the ip/port is the replicated integration api. 

We should have a takeout-startup script that checks it's reachable and correctly reports that.

**Comment by kellihsf** [comment]
If we can't reach that then we can't report the error to the user, might as well just dig through the logs and find this.
