### ISSUE TITLE
Include request logs in support bundle

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io-takeout#127]
The logs are located at `[app root]/logs` by default. You can configure that path via the `WAFFLE_LOGS_DIR` environment variable.

We should consider making them a mounted volume so the files are written out to the host and persist across container starts.

**Comment by homeyer** [comment]
add mongo logs to the support bundle

**Comment by jtslear** [comment]
@burtonjc @homeyer these logs are already in the support bundles.  Am I missing something?

**Comment by homeyer** [comment]
Logs are written to files in takeout, right? 
Defined here: https://github.com/waffleio/waffle.io-helpers/blob/master/src/logger.coffee#L26
Used here: https://github.com/waffleio/waffle.io-api/blob/master/server/src/app.coffee#L20

Are those files included in the support bundle?

**Comment by jtslear** [comment]
I can't find those files......

The app is not throwing errors about not being able to muck with the dir in which those files are supposed to be located.  Are we sure this portion of code actually creates a file?  I think it may be silently failing.

**Comment by jtslear** [comment]
Oh, only the api does this....

Found them in a really awkward location:

```
/src # find / -type d -name logs
/src/node_modules/@waffleio/logs
/src # ls -lah /src/node_modules/@waffleio/logs
total 112
drwxr-xr-x    2 root     root          74 Dec 13 00:00 .
drwxr-xr-x    6 root     root          84 Dec 12 19:58 ..
-rw-r--r--    1 root     root       75.5K Dec 13 13:37 1.waffle-hooks.request.log
-rw-r--r--    1 root     root       35.0K Dec 12 20:48 1.waffle-hooks.request.log.0
```

**Comment by jtslear** [comment]
I'd like to make a suggestion, you tell me some opinions.  Docker contains a logging mechanism.  If we log to stdout and stderr, replicated picks them up.  I'd like to suggest we modify the logger for the apps to utilize this mechanism when run inside of a takeout environment.

The only downside to this is it's now up to the customer to control log rotation via their chosen method of docker/system configuration.  The docker service contains various methods of maintaining logs so this frees the customer to do what they'd prefer.  If necessary, we can point them to the docker configuration doc related to logging should this ever become a problem.  The defaults for docker aren't kind for a production service.

If we don't prefer this, I suggest we revisit how logging is currently working.  [This](https://github.com/waffleio/waffle.io-helpers/blob/master/src/logger.coffee#L29) would need a bit of massaging.
