### ISSUE TITLE
Join link doesn't work on enterprise 🙉

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#138]
When going to <takeout>/:owner/:repo/join, you receive this error message when not logged in.

![image](https://cloud.githubusercontent.com/assets/84629/14395734/a9895f0c-fd90-11e5-9cc0-649a0a774202.png)

**Comment by burtonjc** [comment]
I created https://github.com/waffleio/waffle.io-takeout/issues/148 to fix this problem.

**Comment by burtonjc** [comment]
This will be fixed in the 2.3.0 release. Closing the issue.
