### ISSUE TITLE
Specify the path for the oauth callback in the installation instructions

### ISSUE THREAD

**Issue by zspencer** [waffleio/waffle.io-takeout#139]
Is it `https://<host>/oauth/callback` ? Or is it something else?

![screen shot 2016-04-25 at 5 29 12 pm](https://cloud.githubusercontent.com/assets/50284/14803075/46ca9876-0b0b-11e6-9b73-fa2c013b00d7.png)

**Comment by homeyer** [comment]
Just `https://<host>`

**Comment by zspencer** [comment]
Thanks! Any chance you could make it a bit more explicit in the docs? Or hopefully others will search 'callback' and find this?

**Comment by homeyer** [comment]
yep! https://github.com/waffleio/waffle.io-takeout/pull/140
