### ISSUE TITLE
Provide cycle-time as a metric?

### ISSUE THREAD

**Issue by zspencer** [waffleio/waffle.io-takeout#141]
It would be fantastic if I could also see the cycle time of issues, ideally from a given step to closed. 

Initially, if this is just a scatter-plot with the horizontal axis being the week the issue was closed and the vertical axis being the time it took to close the issue; that would be pretty great.

Later on, if it could do more fancy things with filtering by points or label that would be fantastic.

**Comment by zspencer** [comment]
Anndddd I found the right board for adding this: https://github.com/waffleio/waffle.io/issues/1574

**Comment by kellihsf** [comment]
Lol thanks @zspencer! :)
