### ISSUE TITLE
Deep-linking to a takeout instance seems to not redirect the user to authenticate with github? 🙈

### ISSUE THREAD

**Issue by zspencer** [waffleio/waffle.io-takeout#142]
When I link to an issue or waffle board for a new waffle user, they are greeted with: `{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}`

Could they instead be greated with a "Log in with Github" button?

**Comment by zspencer** [comment]
Also, not sure if this is a "takeout" bug or a regular bug that I should put on the other board :X

**Comment by homeyer** [comment]
Is your GitHub Enterprise configured to allow anonymous access (like an open source GitHub.com repo), or does every repo require you to be authenticated to view it?

**Comment by zspencer** [comment]
It's a regular github.com private repo; we're looking to move to github enterprise "Soon" :tm: but that will likely be in a month or so.

**Comment by burtonjc** [comment]
Opening https://github.com/waffleio/waffle.io-takeout/issues/148 to fix this problem.

**Comment by burtonjc** [comment]
This will be fixed in the 2.3.0 release. Closing the issue.
