### ISSUE TITLE
Waffle Takeout available as AWS AMIs

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#156]
- [x] talk to Replicated first, they have some lessons learned from other customers who have done this
- [x] start with just one ami in US-East-1
- [ ] after, create AMIs for each region, copy GitHub's regions
- [ ] document how these work for customers, and document the upgrade process (should be able to follow the existing upgrade process once you start with an AMI)

**Comment by jtslear** [comment]
how about `us-west-2` instead :-P
