### ISSUE TITLE
Unable to change hostname on Waffle Install

### ISSUE THREAD

**Issue by zspencer** [waffleio/waffle.io-takeout#159]
We installed Waffle temporarily on an Ec2 instance and used their generated domain for the hostl which was fine.

We are now planning to use waffle more extensively and would lik to change the host to something a bit easier to type than `ec2-...-...-..-`.

However the "Hostname" field in settings is read-only.

Is our only option to install a new waffle instance? Or is ther ea config variable somewhere we can edit to change the hostname?

**Comment by homeyer** [comment]
Hey! If you click the gear and go to "console settings" you can change the hostname from there.

**Comment by zspencer** [comment]
Woot! Thanks!
