### ISSUE TITLE
Assignees dropdown for secondary github providers has empty item in it

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io-takeout#163]
Repro steps:
1. Configure Waffle Takeout to auth against one GitHub instance
2. Create a board that has a secondary source from a different GitHub provider
3. Create an issue in the secondary source
4. Open the assignee dropdown on the card for the secondary source

You will see an empty item at the top of the dropdown:

![screen shot 2016-06-16 at 11 49 32 am](https://cloud.githubusercontent.com/assets/443084/16127155/7465b34e-33b8-11e6-9d87-ffbf370c1d32.png)

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
