### ISSUE TITLE
Support HTTPS for waffle takeout

### ISSUE THREAD

**Issue by Kpkero6** [waffleio/waffle.io-takeout#18]
Need ability to provide my own keys/crt to support HTTPS connections via waffle takeout

**Comment by homeyer** [comment]
@Kpkero6 is this blocking you from using Waffle?

**Comment by Kpkero6** [comment]
yes, we can't have data flowing through our network unencrypted

**Comment by jonbrenner** [comment]
@homeyer I just wanted to second what @Kpkero6 said. We're not permitted to use it without TLS.

**Comment by homeyer** [comment]
@Kpkero6 @jonbrenner - we just scheduled this work for this iteration, we'll cut a new build as soon as it's ready. (You can see our work in progress, and what's scheduled in the current iteration on our public roadmap board: https://waffle.io/waffleio/waffle.io)
