### ISSUE TITLE
[spike] - serverless architecture for sync process

### ISSUE THREAD

**Issue by jtslear** [waffleio/waffle.io-takeout#197]
This is a competition to see what's better, using rabbitmq, or waffleio/waffle.io-takeout#198

* [x] Complete a deploy of takeout that includes a running the api which could kick off docker containers as functions
* [x] Look for any risks associated with this work and end result
* [x] Come up with a list of things that ought to be done in order to complete implementation
* [x] Put some focus towards ideas on management and troubleshooting, log gathering, metric pushing

**Comment by jtslear** [comment]
### Risks
* If an on-prem user modifies, for ANY reason how the docker socket is exposed, this will be tough to configure.  In speaking with the replicated fellas, they noted some customers do exactly this.  And if a change is made to the socket file, a support bundle ought to show such.
* A container that gets spun up does NOT inherit any ENV vars passed in from replicated.  So any configuration, such as that for mongo, would need to be passed in when the container is started via nodejs.  Though, this is probably not a risk, just something to keep in mind when coding this work.
* I think the largest risk here is probably the coding work necessary to make this work and the decisions required for enablement.  Infrastructure wise, I literally cannot think of any other reason why this is a bad idea.....

**Comment by jtslear** [comment]
###Feature Completion
* Narrow down the building of the functions inside of docker containers.  Potentially spike out the use of lambda and docker for the exact same set of functions.  This would include testing both infrastructure technologies
* Metrics.  We need to monitor this heavily, for both our aws bill prediction purposes and failures.  For on-prem, we'd need to write to the statsd endpoint that replicated exposes.  For our SaaS I would imagine a custom metric ought to be piped into new relic.
* Logging.

**Comment by songawee** [comment]
👍 This looks awesome!
