### ISSUE TITLE
Burndown charts in Takeout

### ISSUE THREAD

**Issue by desktophero** [waffleio/waffle.io-takeout#204]
I commented on the Waffle.io issue and progress here https://github.com/waffleio/waffle.io/issues/1297. For better tracking at a product level, I thought I would go ahead with an issue here and ask the same question:

Any discussion or thoughts around an ETA when burndowns might drop for Takeout? (assumption: burndowns in Waffle.io will eventually be available in Takeout)

**Comment by burtonjc** [comment]
Tracking this on #205
