### ISSUE TITLE
release metrics on takeout when we release on SaaS

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#205]

**Comment by jtslear** [comment]
* closes #204

**Comment by jtslear** [comment]
* [ ] retag images
* [ ] create beta
  * [ ] need any new env variables?
* [ ] smoke test
* [ ] promote pending results of the above

**Comment by jtslear** [comment]
Blocking, I want waffleio/waffle.io#2864 completed first.
