### ISSUE TITLE
Installation Documentation is not easily found

### ISSUE THREAD

**Issue by jtslear** [waffleio/waffle.io-takeout#207]
Except for the installation doc there doesn't appear to be any place where we show people how to install takeout.  We should think about adding the location of the docs and reoganizing the docs to be better understood:

* [x] Add the install docs to our help page
* [x] Add a link to the install on the takeout site
* [x] Better organize our install docs to avoid a monolithic difficult to understand post
* [x] Modify our intercom emails to include links to the new help docs

**Comment by jtslear** [comment]
https://help.waffle.io/hc/en-us/categories/204580587-Waffle-Takeout

**Comment by songawee** [comment]
Maybe I'm missing it, but I couldn't find - https://github.com/waffleio/waffle.io-takeout/blob/master/INSTALL.md#updating-an-airgap-installation

Has that been re-worded elsewhere or somewhere I didn't look perhaps?

**Comment by songawee** [comment]
sidenote: would be rad if we could enable the page you're currently on as a bread crumb. like, I'm on the "Updating your Waffle Takeout Installation" page, but I only have Waffle.io, Waffle Takeout, Maintenance rather than Waffle.io, Waffle Takeout, Maintenance, Updating Your Waffle Takeout Installation.

**Comment by jtslear** [comment]
I simply missed the airgap upgrade.  I'll add that here shortly.

I'm not sure how to address your comment regarding the navigation style.  We are kinda limited to how zendesk puts the docs together for us.

**Comment by songawee** [comment]
yeah, doesn't look like ZenHub lets you alter the breadcrumbs :( lame. once the airgap stuff is there :+1: :shipit:

**Comment by marydavis** [comment]
did you mean zendesk? lol

**Comment by songawee** [comment]
omg, is it the weekend yet?

**Comment by kellihsf** [comment]
need to update the help links on the auto emails that go out.. configured in mailchimp
