### ISSUE TITLE
build takeout login page and remove existing marketing pages

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#233]
Now that the marketing site is in syrup, we should remove marketing assets from the app.

But, to support Takeout users, we need a simple app-hosted landing page to log you in. This will fix https://github.com/waffleio/waffle.io-takeout/issues/16.

- [ ] remove existing marketing pages, routes, css.
- [ ] create a simple login page for waffle takeout:
  - [ ] Waffle Takeout branding
  - [ ] "Login with GitHub", and always login with private repo access
  - [ ] As a secondary action, link to the github page to grant an organization access

**Comment by AnaMSteele** [comment]
@burtonjc is this the same work that you just completed, and we should close the card as a duplicate?

**Comment by burtonjc** [comment]
Closing as a duplicate. This work is done.
