### ISSUE TITLE
Store snapshots in AWS s3 as appropriate

### ISSUE THREAD

**Issue by desktophero** [waffleio/waffle.io-takeout#234]
Snapshot config to a pre-defined S3 bucket with some creds as inputs would be an awesome feature. Snapshots on the instance in AWS is still a little fragile.

Inputs that specify something similar to:
```
s3-bucket
s3-key
s3-region
ec2-instance-iam-policy-name
```
Would allow me as an admin of both Waffle Takeout and cloud services to setup a versioned, logging-enabled S3 bucket to store the snaps. It would also allow me to specify a policy that allows the specific EC2 instance to write to the location.

I would also expect to have to "click a check box" accepting responsibility to ensure the policy on the bucket is correct. Perhaps this is an "advanced" type of thing.

I could do things like setup cron on my instance and do some aws cli s3 sync type stuff but I'm really interested in the perspective of the community as well as the project to manage snaps.

**Comment by homeyer** [comment]
@desktophero what about setting up a cron job on the host to sync the snapshot to s3?

Using  [aws cli's sync](http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html), something like `aws-cli sync <mysnapshotfolder> <mys3bucket>`.

We haven't tried it, but if that would suffice we can figure out the actual steps.

**Comment by homeyer** [comment]
Ha, just noticed your original comment about using cron + s3 sync, apparently I didn't see that the first time.

We submitted a request to the replicated team to support this, but just as a nice to have feature request.
