### ISSUE TITLE
Dormant users that are suspended in GHE still show as seats used in Takeout

### ISSUE THREAD

**Issue by desktophero** [waffleio/waffle.io-takeout#239]
The current data sets don't map well in showing a number of people who are actually active. License managing is more complex and less trackable.

**Comment by homeyer** [comment]
For GitHub Enterprise, do you have a policy to automatically suspend dormant users or is that a manual process?

Would it work if Waffle tracked `lastLoggedIn` or something similar, and only counted seats against the license for users active in the last 30 days?

**Comment by desktophero** [comment]
Currently, manual (daily admin login). However we're working through a means to make account dormant through some "on appliance" checks. 

For us, the 30 days would make sense since we use that time frame to suspend accounts. If the account is also tied to a Waffle seat, the 30 day period would apply. If they haven't logged into the Waffle app but still have an active GHE account, they shouldn't count anyway towards a Waffle seat consumed.

**Comment by homeyer** [comment]
Thanks. I've prioritized this work, but it won't ship for a few weeks. In the meantime, you can manually clean up users who are no longer on your team with the [admin app](https://help.waffle.io/waffle-takeout/maintenance/waffle-takeout-admin-app).

**Comment by homeyer** [comment]
Implemented, not yet shipped in a takeout release.

**Comment by homeyer** [comment]
Shipped in 2.9.0
