### ISSUE TITLE
link to admin app from server dashboard

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#248]
The admin app isn't discoverable at all, unless you search around help docs.

Let's try to add a link on the replicated dashboard!

**Comment by jtslear** [comment]
This is not possible.  The only place where we can add random stuff would be under the support page, which is fine.  However, replicated doesn't allow that area to be populated with variables.  

I think our next best course of action would be to modify the app in some way.

**Comment by homeyer** [comment]
Cool.

When we do a login page we can add links there.
