### ISSUE TITLE
Mongo Restore Regression?

### ISSUE THREAD

**Issue by jtslear** [waffleio/waffle.io-takeout#254]
Customer reported an issue where restores are causing a lot of interesting behaviors w/i the application:

* [ ] Authentication is not working properly
  * Authorizing the waffle app leaves the end user in an infinite loop of authorizing w/i github 
  * Sometimes the bearer token is not being sent in requests causing 401's
  * Some users are able to utilize waffle ok, while others of the same team are not....
* [ ] Projects are unable to be seen properly
  * If a project should exist in a database, we'll get a 404, which shows up in an awkard spot in the application instead of our standard 404 page
  * If one navigates directly to what would be the name of the project via the URI, we'll get our standard 404 page
* [ ] Current theory is that something changed in 2.9.6 that is causing this behavior
* [ ] recreate
* [ ] find a fix
* [ ] publish a fix

**Comment by homeyer** [comment]
"If a project should exist in a database, we'll get a 404, which shows up in an awkard spot in the application instead of our standard 404 page" - can you describe where in the flow the 404 happens and what the user sees?

**Comment by homeyer** [comment]
Did we confirm that everything is ok with 2.9.5? If so, should we revert 2.9.6? Did the changes for adding `uniqueId` to sources go out with 2.9.6?

**Comment by jtslear** [comment]
Unable to reproduce at this point in time.  Closing for now.
