### ISSUE TITLE
Ship Epics to Takeout

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#259]
Release a new Waffle Takeout build to ship Epics. 
- [ ] Get @kellihsf and @AnaMSteele to help with release notes and a release email.

child of https://rally1.rallydev.com/#/28451149440d/detail/portfolioitem/feature/210195034624

Depends on https://github.com/waffleio/waffle.io-app/issues/1981

**Comment by andybergon** [comment]
Has this been closed because it's done?

**Comment by jtslear** [comment]
Indeed.  Upgrade to 2.10.0.  Hit us up on at support@waffle.io if you have any troubles or have any questions.
