### ISSUE TITLE
HTTP404 redirect loop

### ISSUE THREAD

**Issue by jtslear** [waffleio/waffle.io-takeout#266]
https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/inbox/170193/conversations/17103584234

blocked by https://github.com/waffleio/waffle.io-takeout/issues/16
required by waffleio/hidden#370

**Comment by burtonjc** [comment]
This might be fixed once https://github.com/waffleio/waffle.io-takeout/issues/16 is finished. Just have to confirm
