### ISSUE TITLE
add mongo indices in takeout environments

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io-takeout#35]

**Comment by jtslear** [comment]
@homeyer @burtonjc @songawee I'm seeing indexes on a newly created takeout env.  Is this still an issue?  Did it just get lost on our board?

**Comment by homeyer** [comment]
We're creating indexes in a migration now, so we're all set: https://github.com/waffleio/waffle.io-migrations/blob/master/migrations/20160526182216459_ensure_indexes.coffee
