### ISSUE TITLE
Clarify install docs about DNS settings with subdomains and how SSL works

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io-takeout#37]
There has been a bit of confusion around needing the sub-domains on top of the host domain.

Could we use xip.io to help ease this problem?

For now: 
- [ ] add information around SSL's (ie: need additional certs if can't support wildcard)
- [ ]  clarify second level tld requirement

**Comment by ashumz** [comment]
+ add information around SSL's (ie: need additional certs if can't support wildcard)
