### ISSUE TITLE
'Unable to create card' error on new install

### ISSUE THREAD

**Issue by dlleigh** [waffleio/waffle.io-takeout#43]
No errors on installation, but I get the 'unable to create card' error on the UI after selecting a repo and attempting to create a card.   Using 'docker logs', I see no errors from any apps except the waffle-hedwig app contains many instances of this:

Error { type: 'WebSocketError', error: 'close code 1000' }
newrelic.noticeError (dev): Connection Error: { type: 'WebSocketError', error: 'close code 1000' }
delaying 1 second(s) before connecting...
State changed from connected to disconnected.
State changed from disconnected to connecting.
State changed from connecting to connected.

Any ideas?

**Comment by homeyer** [comment]
Hedwig is used to send outbound webhooks, so that isn't too bothersome. Still shouldn't be erroring out though :).

Can you go to `https://api.<wherever waffle is>`? I'm guessing you'll need to accept the cert there for it to work.

**Comment by homeyer** [comment]
Also, the [DNS section](https://github.com/waffleio/waffle.io-takeout/blob/master/doc/INSTALL.md#prerequisites) in the docs might help, and the [ssl configuration](https://github.com/waffleio/waffle.io-takeout/blob/master/doc/INSTALL.md#ssl-configuration) section.

**Comment by dlleigh** [comment]
Yes, when I go to that URL, I can see the 'It's up' message.

David Leigh
STSM, Project Whitewater
IBM Development Platform
dleigh@us.ibm.com, (919) 254-7129

Learn more about Project Whitewater:  http://www.newwayto.work

**Comment by homeyer** [comment]
Would you mind checking if the org in GitHub is has allowed Waffle?

https://help.github.com/articles/requesting-organization-approval-for-your-authorized-applications/

**Comment by dlleigh** [comment]
We're using Waffle takeout with our GitHub Enterprise.  I have verified
that the org in GHE has allowed Waffle.

David Leigh
STSM, Project Whitewater
IBM Development Platform
dleigh@us.ibm.com, (919) 254-7129

Learn more about Project Whitewater:  http://www.newwayto.work

**Comment by homeyer** [comment]
Sorry for the rabbit chase. A few more things to try:

- If you open up Chrome's debugging console, in the Network tab, do you see anything from the response from the API?

- Do you see any existing issues on your board? If so, are you able to add a label to any of them? What about dragging it to a different column?

**Comment by dlleigh** [comment]
I'm seeing errors like the following in the Chrome debugging console:
Failed to load https://api.waffle.innovate.ibm.com/dleigh/waffletest/cards
resource: net::ERR_INSECURE_RESPONSE

I do not see any existing issues on the board.

David Leigh
STSM, Project Whitewater
IBM Development Platform
dleigh@us.ibm.com, (919) 254-7129

Learn more about Project Whitewater:  http://www.newwayto.work

**Comment by homeyer** [comment]
Can you open https://api.waffle.innovate.ibm.com/dleigh/waffletest/cards in a new tab? Chrome should warn you about the certificate, if you accept the cert from there things should start working.

The real fix is to provide a set of valid certs for Waffle: https://github.com/waffleio/waffle.io-takeout/blob/master/doc/INSTALL.md#trusting-our-root-ca

We're thinking through a way to prevent this from happening, but for now you'll need to accept the certs and either a) have them accepted on your network by your IT group, or b) have your IT group generate certs internally that are accepted on the network, or c) buy certs from somewhere like https://www.rapidssl.com/

**Comment by dlleigh** [comment]
Thanks Andrew!  Accepting the cert solved the problem.   Now I'm off to get
a set of valid certs!

David Leigh
STSM, Project Whitewater
IBM Development Platform
dleigh@us.ibm.com, (919) 254-7129

Learn more about Project Whitewater:  http://www.newwayto.work

**Comment by homeyer** [comment]
:+1: 
Going to close this, feel free to re-open or create a new one if you have trouble installing your certs.

**Comment by dlleigh** [comment]
A follow-up question:  It looks like it may be difficult or impossible to get a wildcard certificate from our company's internal certificate authority.   Is it possible to instead use a set of signed cert files for each of the specific domains needed (e.g. api, admin, hedwig, etc..) ?

**Comment by homeyer** [comment]
yep, that would work fine.

**Comment by dlleigh** [comment]
FYI:  I was able to make it work using a SAN (Subject Alternative Name) certificate instead of a wildcard certificate.   Thanks again for your help.
