### ISSUE TITLE
board updates are not shown until reload

### ISSUE THREAD

**Issue by dlleigh** [waffleio/waffle.io-takeout#49]
Seems to be a websockets issue.  We see this in the browser console:  
`Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006}}}`
And I see this in the waffle-app log:
`newrelic.noticeError (dev): { [PusherRequestError: Request failed with an error]
  name: 'PusherRequestError',
  message: 'Request failed with an error',
  url: 'https://poxa.waffle.XXX:443/apps/pusher-app-id/events?auth_key=pusher-key&auth_timestamp=1440092698&auth_version=1.0&body_md5=6b8dfc9ecb795e98f1797f32753ab6b9&auth_signature=XXXX',
  error: 
   { [Error: SELF_SIGNED_CERT_IN_CHAIN]`
And I see this in the waffle-poxa log:
`18:49:28.335 [error] Error in process <0.28922.0> with exit value: {[{reason,function_clause},{mfa,{'Elixir.Poxa.WebsocketHandler',websocket_handle,3}},{stacktrace,[{'Elixir.Poxa.WebsocketHandler',websocket_handle,[{ping,<<4 bytes>>},{http_req,#Port<0.12876>,ranch_tcp,keepalive,<0.28922.0>,<<3 bytes>>,'HTTP/1.1',{{172,17,0,87},50531},<<28 bytes>>,undefined... `
Despite the error message, we are not using a self-signed certificate.  We are currently using a Subject Alternative Name certificate instead of a wildcard certificate.

**Comment by ashumz** [comment]
Hi @dlleigh, 

Just wanted to let you know this is on our radar. We're planning to rework the way this acts in the near future, so you can continue to follow along on this card. Keep us posted if you have questions or major blocking issues in the meantime as we work towards a fix for this.

Ashley

**Comment by homeyer** [comment]
@dlleigh, we just wrapped up some work to condense how we use certificates. Instead of poxa, api, etc being discoverable via subdomains, we're using an `nginx` configuration to route them via paths (e.g., `your.takeout.io/api`, instead of `api.your.takeout.io`).

We're targeting a release the week of Oct 5th, which will also include some other improvements.

**Comment by dlleigh** [comment]
:+1:

**Comment by homeyer** [comment]
closing this out, the latest build available on takeout.waffle.io fixes realtime issues.
