### ISSUE TITLE
Allow Boards to be Public

### ISSUE THREAD

**Issue by Snugug** [waffleio/waffle.io-takeout#52]
Right now, a user needs to be part of the GitHub Enterprise team in order to view a board, but there are times where we'd like to share out a board to those not in the GitHub Enterprise team. I'd like the option, on a board-by-board basis, to make them available w/o login

**Comment by homeyer** [comment]
Hey @Snugug - is your repo private in GH:E, or public? Would it be possible to have a public board, even if it's for issues only? That would let us still respect GitHub's permissions, but let anyone see your Waffle board.

**Comment by Snugug** [comment]
It's public

**Comment by homeyer** [comment]
Whoops, super late reply, sorry!

In your GH:E setup there's this setting:
![image](https://cloud.githubusercontent.com/assets/84629/10651213/733ff150-780b-11e5-8d9d-d0f54cc62476.png)

If that's disabled, then anyone can view your repo without logging in to GH:E. Then, you should be able to view the board for that repo also without logging in.

**Comment by homeyer** [comment]
If your GH:E is open to the internet though, I think it's against the GH:E ToS to turn that setting off.
