### ISSUE TITLE
Ranking is not preserved when including multiple sources in a Kanban

### ISSUE THREAD

**Issue by dlleigh** [waffleio/waffle.io-takeout#53]
To reproduce:
1. Create a git repository for Team A, which will also contain an associated issues repository.
2. Create a Kanban board for the repository in (1).  This will be the Kanban board that Team A will work from.
3. Create another git repository.  For the same of this discussion, let's call it "waffle-rollup".
4. Create a Kanban board for the repository in (3).  This Kanban board will be to aggregate multiple Kanban boards into one.
5.  In Team A's Kanban board, pick a lane and order cards within that lane.
6. In the rollup Kanban board, filter the board down to only show Team A's Kanban board.

Expected Result:
The "roll up" Kanban board contains the same card ordering.

Actual Result:
The "roll up" Kanban board contains a different order.

Use Case 1: We would like to provide management with a single dashboard that they can filter down to view team priorities without having to go down into each individual board.  The "roll up" board will have a different view than the "team boards".  Best practice will be that it's "read only".

Use Case 2:  A scrum team of 4-5 people would like to use waffle to manage the task-level work to accomplish 1 user story.   They create issues in the 3 repos where work is needed to implement the story, using a milestone to mark those issues as part of the story.   They create a multi-source waffle board, using a filter to show only those tasks related to the story.  Due to this issue, they cannot prioritize the tasks on the board.

**Comment by niemela** [comment]
+1

**Comment by specky-rum** [comment]
Use Case 3: A project is provided to multiple clients but we only want each client to see their own issues plus the generic project issues. (note: Currently GitHub permissions are not entirely respected as it is possible to create a single project board, add 3 repos and users will see all issues regardless of repo permissions as long as they have access to the primary repo.)  Instead we create a separate project board for each client and add their repo and the main project repo, then we have another project board with the main repo and ALL client repos for the developers.  Problem now being that if the client reorders their board this order is not reflected on the main board and developers can't see the client's priorities.

**Comment by dmcsorley** [comment]
+1

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
