### ISSUE TITLE
smaller Docker containers

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#61]
**Acceptance Criteria**
- [x] use alpinelinux as the base image
- [x] use the codeship webinar's trick to add the `package.json` and run `npm install --production` as early commands to have a layer that doesn't change, before adding source code
- [x] use the alpine image for the latest node (5.4?)
- [x] leave migrations at 0.10, everything else will work with 5

i think this will work:
- do `docker build .` locally for an image
- push up to quay with a tag
- do an unstable replicated yaml for that tag
- if that works, iterate locally with `docker build .` for the other containers, until they all build, then push them all with tags and do a yaml
- at the end, we should have PRs for each repo's dockerfile

**Comment by burtonjc** [comment]
We need to upgrade to node 5 at the same time. Use the base image `mhart/alpine-node:5.0`
