### ISSUE TITLE
decide on how to version Takeout releases

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io-takeout#7]
Consider using GitHub releases for this? 

current thought (from @burtonjc): we already do versions for all of our other repos, and it'd be burdensome to do a different versioning system. we could install Grunt and use the same Grunt task we use everywhere else for uploading and updating the version to S3.

@homeyer - can you comment on this /if it's how we want to do it this way?

**Comment by homeyer** [comment]
resolved! :)
