### ISSUE TITLE
Allow Takeout to work without SSL

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io-takeout#81]
Currently we require a secure connection in order to install and run Takeout. We've had [a few](https://app.intercom.io/a/apps/fb774a034de340cde33822ae0c071ad60efe899f/inbox/takeout-follow-up/conversations/1309982821) requests to allow Takeout to work with GitHub running on http, instead of only https.

**Acceptance Criteria**
- [ ] nginx configuration for running on port 80
 - [ ] make sure poxa works
- [ ] configuration on replicated settings screen for "secure" or "insecure"

**Comment by sgredell** [comment]
Is it still the case that Takeout will not run without using SSL?  Are there any workarounds to make it possible or will we have to set up SSL in our GH:E appliance?

Thanks

**Comment by homeyer** [comment]
Still requires SSL @sgredell, sorry about that! We're planning on removing that requirement though.

**Comment by nparsons08** [comment]
Auto redirect to HTTPS when available

**Comment by nmosafi** [comment]
Still no progress on this I take it?

**Comment by homeyer** [comment]
Not yet!

If you're able to switch GitHub Enterprise to use SSL we can show you how to generate a free trusted cert with [LetsEncrypt](https://letsencrypt.org/).

**Comment by songawee** [comment]
Hey @sgredell, @nmosafi!

We just released Waffle Takeout 2.4.3 that allows you to run Waffle Takeout without SSL. This allows you to connect to a GitHub Enterprise instance that does not have SSL enabled. Please let us know if you have any questions or issues.

Thanks!
