### ISSUE TITLE
Flexibility in github labels

### ISSUE THREAD

**Issue by mbeaton** [waffleio/waffle.io-takeout#93]
I'm trying to facilitate 'cascading' boards, whereby a 'Story' is defined at the 'root' level board, and essentially goes through a lifecycle in sub-boards. And example would be like so. In the root level board, I want to know all Stories that are in 'design' phase, but, I only really want to know whether it's in progress vs completed. In the root board, I can put the Story in 'design - needed' column. In the 'Design' board, this shows up in their left most column, matching 'design - needed'. Within their board, they move the Story through the various states as the board defines. For example, in progress, under review, completed, etc. They would prefix each of these column github labels with 'design -', to indicate it's a design state. In the root board, I only care whether it's in progress or completed. In progress, at the root board, I'd like to define as 'design - in progress OR design - under review', as both are technically NOT completed in this context. The problem, however, is that I can define only 1 of those labels. Meaning, I can have a column in my board called 'design - in progress', and that works fine. The minute the Design board moves the item into 'design - under review', it ends up in my backlog column.

What I'd like is to define a column at the root board, called 'Design (in progress)'. The github label for this could be:
1) [design - in progress, design - under review]
2) design - in progress OR design - under review

Am I attempting to do something this was just not designed for? Is there a recommendation on how to achieve the above, without creating every column in the 'root' board?

**Comment by kellihsf** [comment]
Hey @mbeaton! Sorry for not responding earlier!

We don't currently support meta boards like what you're talking about. Interesting idea, and we do want to support better ways to roll up and plan work. But, you're stuck with a parent board showing all the columns of the sub boards to do what you're talking about.

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
