### ISSUE TITLE
validate github username on signup form on takeout management site

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io-takeout#98]
We often get requests for takeout where the user doesn't give us their GitHub.com username, and we have to email them and manually update the db when they give it to us.

**Acceptance Criteria**
- [x] make a `GET` request to `https://api.github.com/users/:username` to see if the user exists or not
- [x] have a hover tooltip for why we require it on a question mark icon
- [x] use an anonymous token so we don't hit the API limits. Add it as an env var, use the same one we have in the app for `APPLICATION_ACCESS_TOKEN`, but let's call it `GITHUB_ANONYMOUS_ACCESS_TOKEN` instead :).

**Comment by marydavis** [comment]
- [ ] check upon entering GitHub username - with delay
- [ ] disable submit button unless valid
